### ISSUE TITLE
Sticky top nav is broken

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Wordpress-Theme#196]
I can't get it to stick on any of our sites in any of my browsers. Also there are no console errors.

**Comment by idmontie** [comment]
Need to add the following rule:

```css
.navbar-ws.active {
  position: fixed;
}
```
