### ISSUE TITLE
5-column mega menu

### ISSUE THREAD

**Issue by stephmabee** [gios-asu/ASU-Web-Standards-Wordpress-Theme#202]
So, we did a soft-launch of the Engineering homepage today. One of our mega-menus has five columns and the left and right padding/margins gets a little weird. http://engineering.asu.edu/ 

The mega menu in question is the "Degrees" option.

**Comment by rraub** [comment]
Congrats! We have been trying to use the "Mega menu" less and less, it seems that presenting users with too many choices per drop down makes things harder to find. That being said it should at least have the same padding as the other mega menus.

Just posting a screen shot so we have record of what it looks like.
![screen shot 2015-12-28 at 10 11 36 am](https://cloud.githubusercontent.com/assets/295804/12022265/6c0cd7ca-ad4b-11e5-89fd-a86876d0945b.png)

**Comment by rraub** [comment]
This actually wont be as straight forward as I was hoping. Bootstrap gives us 12 columns per row to work with and 5 items don't fit evenly into the 12 columns. We could make the first and last columns one unit wider which would look like this:
![screen shot 2015-12-28 at 11 37 02 am](https://cloud.githubusercontent.com/assets/295804/12023503/5b2c8c6e-ad57-11e5-80e9-e4c1dfe94b47.png)

The solutions for supporting 5 evenly spaced columns are not pretty and this is the first instance we've come up with needing it. I'm curious with @idmontie thinks about this when he gets back from vacation.

**Comment by stephmabee** [comment]
I agree that there's such a thing as too many choices. :) This was my first attempt at making our old IA fit the new standards.

I wondered if the "odd" number of columns was a problem. I could make it four columns and pull Student Success up a level to be just a dropdown menu next to Degrees.

**Comment by rraub** [comment]
Moving the 5th column up would be the quickest fix.

FYI: The Hub has [some guidelines](https://brandguide.asu.edu/web-standards/academic/information-architecture) when it comes to a few of the top and secondary level menu items. Its really hard to find on their site, but I would expect you to get some feedback at some point about the required items they want.

**Comment by stephmabee** [comment]
I tried to follow the guidelines as much as possible. I imagine there will be feedback cycles. I did move Student Success up and the four-column mega menu definitely works better. I suppose I could change "Student Success" to "Student Life" to be more in-line.

**Comment by idmontie** [comment]
Now that I am back, here is my proposed solution:

The 12 column layout of Boostrap allows for 1, 2, 3, 4, and 6 columns since they divide 12 equally. Anything over 6 I don't think should be supported.

5 seems like a reasonable number of columns to support. W can support it by adding some CSS to our base theme:

[Source](http://stackoverflow.com/a/22799354/759316)

```css
.col-xs-5ths,
.col-sm-5ths,
.col-md-5ths,
.col-lg-5ths {
    position: relative;
    min-height: 1px;
    padding-right: 10px;
    padding-left: 10px;
}

.col-xs-5ths {
    width: 20%;
    float: left;
}

@media (min-width: 768px) {
    .col-sm-5ths {
        width: 20%;
        float: left;
    }
}

@media (min-width: 992px) {
    .col-md-5ths {
        width: 20%;
        float: left;
    }
}

@media (min-width: 1200px) {
    .col-lg-5ths {
        width: 20%;
        float: left;
    }
}
```

And then we just add a rule to the menu builder that if there are 5 columns, it uses the col-md-5ths.
